version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8081
      - SERVER_ENVIRONMENT=dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
